import {useEffect,useState,type FormEvent} from "react";
import {CalendarDays,Check,CloudUpload,FlaskConical,Plus} from "lucide-react";
import {toast} from "sonner";
import Picker from "@/components/field-picker";
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from "@/components/ui/table";
import {todayLima,isoWeek,type Measurement} from "@/lib/riego-model";
import {WATER_PARAMETERS,waterFilters,emptyWaterValues,changeWaterContext,makeWaterQualityRecord,type WaterContext} from "@/lib/calidad-agua";

type Props={records:Measurement[];busy:boolean;online:boolean;onSave:(record:Measurement)=>Promise<void>};
const numberLabel=(value:number|undefined)=>value==null?"—":value.toLocaleString("es-PE",{maximumFractionDigits:3});
export function WaterReadingFields({ready,values,onChange}:{ready:boolean;values:ReturnType<typeof emptyWaterValues>;onChange:(key:typeof WATER_PARAMETERS[number]["key"],value:string)=>void}){
  if(!ready)return <p className="water-prompt">Selecciona fecha, sede y filtrado para ingresar pH, CE, Na y Ca.</p>;
  return <section className="water-profile" aria-label="Parámetros de calidad de agua"><div className="humidity-heading"><span>Parámetro</span><span>Valor</span></div>{WATER_PARAMETERS.map(parameter=><label className="field humidity-row" key={parameter.key}><span>{parameter.label}</span><input type="number" inputMode="decimal" step="any" min={0} value={values[parameter.key]} onChange={event=>onChange(parameter.key,event.target.value)} aria-label={`${parameter.label} del agua`} required/></label>)}</section>;
}
export function WaterLocationFields({context,onChange}:{context:WaterContext;onChange:(key:keyof WaterContext,value:string)=>void}){
  return <div className="form-grid"><label className="field"><span>Fecha</span><input type="date" value={context.date} onChange={event=>onChange("date",event.target.value)} required/></label><Picker label="Sede" value={context.lugar} onChange={value=>onChange("lugar",value)} options={["OLMOS","MOTUPE"].map(value=>({value,label:value}))}/><div className="wide"><Picker label="Filtrado" value={context.filtrado} onChange={value=>onChange("filtrado",value)} options={[{value:"",label:"Selecciona un filtrado"},...waterFilters(context.lugar).map(value=>({value,label:value}))]}/></div></div>;
}
export default function WaterQualityCapture({records,busy,online,onSave}:Props){
  const [context,setContext]=useState<WaterContext>({date:todayLima(),lugar:"OLMOS",filtrado:""}),[values,setValues]=useState(emptyWaterValues),[saving,setSaving]=useState(false);
  useEffect(()=>{setValues(emptyWaterValues());},[context.date,context.lugar,context.filtrado]);
  const filters=waterFilters(context.lugar),ready=Boolean(context.date&&context.lugar&&filters.includes(context.filtrado)),disabled=busy||saving;
  const rows=records.filter(record=>record.kind==="CALIDAD_AGUA");
  async function submit(event:FormEvent){event.preventDefault();if(disabled)return;setSaving(true);try{await onSave(makeWaterQualityRecord(context,values));setValues(emptyWaterValues());}catch(error){toast.error((error as Error).message);}finally{setSaving(false);}}
  return <div className="capture-grid"><section className="panel capture-panel"><div className="panel-heading"><div className="section-icon"><FlaskConical/></div><div><p className="eyebrow">NUEVO REGISTRO</p><h2>Calidad de agua</h2></div></div><form onSubmit={submit}><fieldset className="capture-fields" disabled={disabled}><WaterLocationFields context={context} onChange={(key,value)=>setContext(previous=>changeWaterContext(previous,key,value))}/><div className="date-meta"><CalendarDays size={15}/>Año {context.date.slice(0,4)}<span>Mes {Number(context.date.slice(5,7))||"—"}</span><span>Semana {context.date?isoWeek(context.date):"—"}</span></div><div className="measurement-fields"><WaterReadingFields ready={ready} values={values} onChange={(key,value)=>setValues(previous=>({...previous,[key]:value}))}/></div><button className="primary full save" disabled={disabled||!ready}><Plus size={19}/>{disabled?"Guardando…":"Guardar calidad de agua"}</button><p className="form-note">{online?"Se guarda en la app. Sincroniza para enviarla a Drive.":"Se guarda en este dispositivo. Sincroniza al volver la conexión."}</p></fieldset></form></section>
    <section className="panel recent-panel"><div className="panel-heading between"><div><p className="eyebrow">HISTORIAL</p><h2>Últimos registros de agua</h2></div><span className="count-chip">{rows.length}</span></div>{rows.length?<Table className="record-table water-record-table"><TableHeader><TableRow><TableHead>Fecha / sede</TableHead><TableHead>Filtrado</TableHead>{WATER_PARAMETERS.map(parameter=><TableHead key={parameter.key}>{parameter.label}</TableHead>)}<TableHead>Estado</TableHead></TableRow></TableHeader><TableBody>{rows.slice(0,12).map(record=><TableRow key={record.id}><TableCell><strong>{record.date.split("-").reverse().join("/")}</strong><small>{record.lugar}</small></TableCell><TableCell>{record.filtrado}</TableCell>{WATER_PARAMETERS.map(parameter=><TableCell key={parameter.key}>{numberLabel(record[parameter.key])}</TableCell>)}<TableCell><span className={`record-status ${record.synced?"done":"waiting"}`}>{record.synced?<Check size={13}/>:<CloudUpload size={13}/>} {record.pending?"Dispositivo":record.synced?"Drive":"App"}</span></TableCell></TableRow>)}</TableBody></Table>:<div className="analytics-empty"><strong>Todavía no hay registros de agua</strong><p>Completa los parámetros del filtrado o sincroniza los datos de Drive.</p></div>}</section>
  </div>;
}
