import {readFile,writeFile,copyFile,mkdir} from "node:fs/promises";
const root=new URL("../",import.meta.url);
const pkg=JSON.parse(await readFile(new URL("package.json",root),"utf8"));
const [major,minor,patch]=pkg.version.split(".").map(Number);
if([major,minor,patch].some(n=>!Number.isInteger(n)||n<0||n>999))throw new Error("Versión Android inválida");
const vars=new URL("android/variables.gradle",root);
await writeFile(vars,(await readFile(vars,"utf8")).replace(/minSdkVersion\s*=\s*\d+/,"minSdkVersion = 26"));
const gradle=new URL("android/app/build.gradle",root);
let text=await readFile(gradle,"utf8");
text=text.replace(/versionCode\s+\d+/,`versionCode ${major*1000000+minor*1000+patch}`).replace(/versionName\s+"[^"]+"/,`versionName "${pkg.version}"`);
// Sign release builds only with credentials supplied outside the repository.
if(!text.includes("RIEGO_KEYSTORE_PATH"))text+=`\nif (System.getenv('RIEGO_KEYSTORE_PATH')) {\n    android.signingConfigs.create('riegoRelease') {\n        storeFile file(System.getenv('RIEGO_KEYSTORE_PATH'))\n        storePassword System.getenv('RIEGO_KEYSTORE_PASSWORD')\n        keyAlias System.getenv('RIEGO_KEY_ALIAS')\n        keyPassword System.getenv('RIEGO_KEY_PASSWORD')\n    }\n    android.buildTypes.release.signingConfig = android.signingConfigs.riegoRelease\n}\n`;
if(!text.includes('riegoStableDebug'))text+=`\n// riegoStableDebug: certificate for development builds only.\nandroid.signingConfigs.debug {\n    storeFile rootProject.file('../scripts/android-debug.keystore')\n    storePassword 'android'\n    keyAlias 'androiddebugkey'\n    keyPassword 'android'\n}\n`;
await writeFile(gradle,text);
const manifest=new URL("android/app/src/main/AndroidManifest.xml",root);
let xml=await readFile(manifest,"utf8");
if(!xml.includes('android:scheme="riego"'))xml=xml.replace("</activity>",`    <intent-filter>\n                <action android:name="android.intent.action.VIEW" />\n                <category android:name="android.intent.category.DEFAULT" />\n                <category android:name="android.intent.category.BROWSABLE" />\n                <data android:scheme="riego" android:host="activate" />\n            </intent-filter>\n        </activity>`);
xml=xml.replace(/android:allowBackup="true"/, 'android:allowBackup="false"');
await writeFile(manifest,xml);
// Reuse the already inspected droplet icon as the launcher icon.
const res=new URL("android/app/src/main/res/",root);
for(const name of ["mipmap-mdpi","mipmap-hdpi","mipmap-xhdpi","mipmap-xxhdpi","mipmap-xxxhdpi"]){
 await mkdir(new URL(name+"/",res),{recursive:true});
 for(const icon of ["ic_launcher.png","ic_launcher_round.png","ic_launcher_foreground.png"])await copyFile(new URL("public/icon-512.png",root),new URL(name+"/"+icon,res));
}
// The splash drawables generated by Capacitor remain valid without external assets.
console.log(`Android preparado: Riego ${pkg.version}, Android 8 o posterior.`);
