"use client";
import {useState,useEffect,useRef,useMemo,type FormEvent} from "react";
import FieldMap from "@/components/riego-map";
import RiegoOnboarding,{type ActivationInput} from "@/components/riego-onboarding";
import {Capacitor} from "@capacitor/core";
import {App as NativeApp} from "@capacitor/app";
import {api,configuredEndpoint,configureEndpoint,AccessError,type Snapshot} from "@/lib/api";
import {parseAccess,accessLink} from "@/lib/access";
import {scanAccess,shareQr,shareText} from "@/lib/native";
import scriptSource from "../apps-script/Riego.gs?raw";
import {Droplets,Gauge,Layers,ChartNoAxesCombined,MapPinned,RefreshCw,Plus,Wifi,WifiOff,LogOut,QrCode,Download,Check,Copy,MapPin,CalendarDays,Inbox,CloudUpload} from "lucide-react";
import {LineChart,Line,BarChart,Bar,XAxis,YAxis,CartesianGrid,Tooltip,Legend,ResponsiveContainer} from "recharts";
import QRCode from "qrcode";
import {Tabs,TabsList,TabsTrigger,TabsContent} from "@/components/ui/tabs";
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from "@/components/ui/select";
import {Dialog,DialogContent,DialogTitle,DialogDescription} from "@/components/ui/dialog";
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from "@/components/ui/table";
import {Empty,EmptyHeader,EmptyTitle,EmptyDescription} from "@/components/ui/empty";
import {Toaster,toast} from "sonner";
import {KINDS,LABELS,recordSchema,todayLima,isoWeek,normalize,featureLocation,mean,matchesFeature,reading,type Kind,type Measurement,type GeoCollection} from "@/lib/riego-model";
import {cached,cache,queued,enqueue,acknowledge} from "@/lib/riego-offline";
import "leaflet/dist/leaflet.css";

type InstallEvent=Event & {prompt:()=>Promise<void>;userChoice:Promise<{outcome:string}>};
const COLORS=["#087a63","#3179ba","#cc8131","#805bc3","#c15168","#087f91"];
const NAV=[{id:"HUMEDADES",label:"Humedades",icon:Droplets},{id:"COMPACTACION",label:"Compactación",icon:Layers},{id:"PRESIONES",label:"Presiones",icon:Gauge},{id:"graficas",label:"Gráficas",icon:ChartNoAxesCombined},{id:"mapa",label:"Mapa",icon:MapPinned}];
function Picker({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:{value:string;label:string}[]}){return <label className="field"><span>{label}</span><Select value={value} onValueChange={onChange}><SelectTrigger className="picker" aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{options.map(o=><SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>)}</SelectContent></Select></label>;}
function dateLabel(v:string){return v?v.split("-").reverse().join("/"):"—";}
function num(v:number|null|undefined){return v==null?"—":v.toLocaleString("es-PE",{maximumFractionDigits:2});}
function Blank({title,detail}:{title:string;detail:string}){return <Empty className="blank"><EmptyHeader><Inbox size={30} className="blank-icon"/><EmptyTitle>{title}</EmptyTitle><EmptyDescription>{detail}</EmptyDescription></EmptyHeader></Empty>;}
function NumberField({label,name,form,update,max}:{label:string;name:string;form:Record<string,string>;update:(f:Record<string,string>)=>void;max?:number}){return <label className="field"><span>{label}</span><input type="number" inputMode="decimal" step="any" min={0} max={max} value={form[name]} onChange={e=>update({...form,[name]:e.target.value})} required/></label>;}

export default function Page(){
 const [tab,setTab]=useState("HUMEDADES"),[snapshot,setSnapshot]=useState<Snapshot|null>(null),[queue,setQueue]=useState<Measurement[]>([]),[authorized,setAuthorized]=useState(false),[loaded,setLoaded]=useState(false),[online,setOnline]=useState(true),[busy,setBusy]=useState(false),[problem,setProblem]=useState("");
 const [sharedEntry,setSharedEntry]=useState(0);
 const [connectDraft,setConnectDraft]=useState(""),[code,setCode]=useState(""),[settingsOpen,setSettingsOpen]=useState(false),[scriptUrl,setScriptUrl]=useState(""),[unitDraft,setUnitDraft]=useState<Record<string,string>>({}),[invite,setInvite]=useState<{code:string;expiresAt:number;qr:string;url:string}|null>(null),[install,setInstall]=useState<InstallEvent|null>(null);
 const [kind,setKind]=useState<Kind>("HUMEDADES"),[lugar,setLugar]=useState("all"),[fundo,setFundo]=useState("all"),[lote,setLote]=useState("all"),[from,setFrom]=useState(""),[to,setTo]=useState(""),[dimension,setDimension]=useState("all"),[metric,setMetric]=useState("m1");
 const inFlight=useRef(false),mapInput=useRef<HTMLInputElement>(null);
 const [form,setForm]=useState<Record<string,string>>({date:todayLima(),lugar:"OLMOS",fundo:"",modulo:"",lote:"",prof:"",humedad:"",puntos:"",m1:"",m2:"",m3:"",lado:"",presion:""});
 const formKind=(KINDS as readonly string[]).includes(tab)?tab as Kind:null;
 const all=useMemo(()=>{const rows=new Map((snapshot?.records??[]).map(r=>[r.id,r]));queue.forEach(r=>rows.set(r.id,{...r,pending:true}));return [...rows.values()].sort((a,b)=>b.date.localeCompare(a.date));},[snapshot,queue]);
 async function acceptSnapshot(s:Snapshot){setSnapshot(s);setScriptUrl(s.scriptUrl??"");setUnitDraft(s.units??{});await cache("snapshot",s);}
 async function flush(){while(inFlight.current)await new Promise(resolve=>setTimeout(resolve,40));if(!navigator.onLine)return;inFlight.current=true;try{const pending=await queued();for(let i=0;i<pending.length;i+=100){const {saved}=await api<{saved:string[]}>("save",{records:pending.slice(i,i+100)});await acknowledge(saved);}setQueue(await queued());await acceptSnapshot(await api<Snapshot>("records"));setProblem("");}finally{inFlight.current=false;}}
 useEffect(()=>{
  let cancelled=false;const on=()=>{setOnline(true);void flush().catch(e=>{if(e instanceof AccessError)setAuthorized(false);setProblem(e.message);});},off=()=>setOnline(false),installHandler=(e:Event)=>{e.preventDefault();setInstall(e as InstallEvent);};
  window.addEventListener("online",on);window.addEventListener("offline",off);window.addEventListener("beforeinstallprompt",installHandler);setOnline(navigator.onLine);
  void(async()=>{try{const old=await cached<Snapshot>("snapshot");if(old&&!cancelled){setSnapshot(old);setUnitDraft(old.units);setScriptUrl(old.scriptUrl??"");}setQueue(await queued());const hash=new URLSearchParams(location.hash.slice(1));let entry=hash.get("codigo");const server=hash.get("servidor");if(server)await configureEndpoint(server);if(Capacitor.isNativePlatform()){const launch=await NativeApp.getLaunchUrl();if(launch?.url){const a=parseAccess(launch.url);entry=a.code;if(a.endpoint)await configureEndpoint(a.endpoint);}}setConnectDraft(await configuredEndpoint()??"");if(entry){setCode(entry);setSharedEntry(v=>v+1);history.replaceState(null,"",location.pathname+location.search);}if(!navigator.onLine){setAuthorized(Boolean(await cached("activated")));return;}let access=await api<{ok:boolean;owner:boolean}>("status");if(!access.ok&&entry){await api("activate",{code:entry,principal:false});access=await api("status");}if(cancelled)return;setAuthorized(access.ok);await cache("activated",access.ok);if(access.ok)await flush();}catch(e){if(!cancelled){setAuthorized(e instanceof AccessError?false:Boolean(await cached("activated")));if(e instanceof AccessError)setAuthorized(false);setProblem((e as Error).message);}}finally{if(!cancelled)setLoaded(true);}})();
  if(!Capacitor.isNativePlatform()&&"serviceWorker"in navigator)void navigator.serviceWorker.register(import.meta.env.BASE_URL+"sw.js").then(async()=>{
   const registration=await navigator.serviceWorker.ready;
   await import("leaflet");
   const urls=[new URL("./",location.href).href,...performance.getEntriesByType("resource").map(e=>e.name).filter(name=>{const url=new URL(name,location.origin);return url.origin===location.origin&&/\.(js|css)$/.test(url.pathname);})];
   registration.active?.postMessage({type:"CACHE_SHELL",urls});
  }).catch(()=>{});
  return()=>{cancelled=true;window.removeEventListener("online",on);window.removeEventListener("offline",off);window.removeEventListener("beforeinstallprompt",installHandler);};
 // eslint-disable-next-line react-hooks/exhaustive-deps
 },[]);
 useEffect(()=>{const context=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>unknown}}).modelContext;if(!context||!authorized)return;const controller=new AbortController();try{void Promise.resolve(context.registerTool({name:"open_riego_section",title:"Abrir apartado de riego",description:"Abre un apartado de riego sin guardar mediciones.",inputSchema:{type:"object",properties:{section:{type:"string",enum:NAV.map(n=>n.id)}},required:["section"],additionalProperties:false},annotations:{readOnlyHint:true},execute:async(input:unknown)=>{const section=(input as {section?:string})?.section;if(!NAV.some(n=>n.id===section))throw new Error("Apartado inválido");setTab(section!);await new Promise(resolve=>setTimeout(resolve,0));return {section};}},{signal:controller.signal})).catch(()=>{});}catch{}return()=>controller.abort();},[authorized]);
 async function activateDevice(input:ActivationInput){
  setBusy(true);setProblem("");
  try{
   let endpoint=input.endpoint,code=input.code;
   if(!input.principal){const access=parseAccess(code);code=access.code;if(access.endpoint){endpoint=access.endpoint;setConnectDraft(endpoint);}}
   if(endpoint)await configureEndpoint(endpoint);
   await api("activate",{code,principal:input.principal,name:input.name});
   await cache("activated",true);setAuthorized(true);await flush();setCode("");
  }catch(e){if(e instanceof AccessError)setAuthorized(false);setProblem((e as Error).message);}finally{setBusy(false);}
 }
 async function submit(e:FormEvent){e.preventDefault();if(!formKind)return;setBusy(true);setProblem("");try{const raw:Record<string,unknown>={id:crypto.randomUUID(),kind:formKind,date:form.date,lugar:form.lugar,fundo:form.fundo,modulo:form.modulo,lote:form.lote};const fields=formKind==="HUMEDADES"?["prof","humedad"]:formKind==="COMPACTACION"?["m1","m2","m3"]:["presion"];for(const k of fields){if(form[k]==="")throw new Error("Completa todas las mediciones.");raw[k]=Number(form[k].replace(",","."));}if(formKind==="COMPACTACION")raw.puntos=form.puntos;if(formKind==="PRESIONES")raw.lado=form.lado;const result=recordSchema.safeParse(raw);if(!result.success)throw new Error(result.error.issues[0].message);await enqueue(result.data);setQueue(await queued());setForm(prev=>({...prev,humedad:"",m1:"",m2:"",m3:"",presion:""}));if(navigator.onLine){try{await flush();toast.success("Medición guardada en la app.");}catch(e){if(e instanceof AccessError)setAuthorized(false);setProblem((e as Error).message);toast("Guardada en este dispositivo; pendiente de enviar.");}}else toast.success("Medición guardada sin conexión.");}catch(e){if(e instanceof AccessError)setAuthorized(false);setProblem((e as Error).message);}finally{setBusy(false);}}
 async function sync(){setBusy(true);try{await flush();const s=await api<Snapshot&{written:number;read:number}>("sync",{});await acceptSnapshot(s);toast.success(`Drive actualizado: ${s.written} enviados, ${s.read} registros disponibles.`);setProblem("");}catch(e){if(e instanceof AccessError)setAuthorized(false);setProblem((e as Error).message);}finally{setBusy(false);}}
 async function logout(){if(queue.length){toast.error("Envía primero las mediciones pendientes de este dispositivo.");return;}if(!online){toast.error("Conéctate para cerrar el acceso.");return;}try{await api("logout",{});setAuthorized(false);setSnapshot(null);setProblem("");}catch(e){if(e instanceof AccessError)setAuthorized(false);setProblem((e as Error).message);}}
 async function makeInvite(){setBusy(true);try{const r=await api<{code:string;expiresAt:number}>("invite",{});const url=accessLink(scriptUrl,r.code);setInvite({...r,url,qr:await QRCode.toDataURL(url,{width:280,margin:2,color:{dark:"#064d40",light:"#ffffff"}})});}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}}
 async function saveSettings(){setBusy(true);try{await acceptSnapshot(await api<Snapshot>("config",{scriptUrl,units:unitDraft}));toast.success("Unidades guardadas.");setProblem("");}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}}
 async function importMap(file:File){if(file.size>3000000){toast.error("Carga un GeoJSON menor a 3 MB.");return;}setBusy(true);try{await acceptSnapshot(await api<Snapshot>("config",{geojson:JSON.parse(await file.text())}));toast.success("Mapa de lotes cargado.");}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}}
 const locations=useMemo(()=>[...(snapshot?.geojson?.features.map(featureLocation)??[]),...all.map(r=>({lugar:r.lugar,fundo:r.fundo,modulo:r.modulo,lote:r.lote}))],[snapshot?.geojson,all]);
 const unique=(key:"lugar"|"fundo"|"lote",rows=locations)=>[...new Set(rows.map(l=>l[key]).filter(Boolean))].sort();
 const analysis=all.filter(r=>r.kind===kind&&(lugar==="all"||r.lugar===lugar)&&(fundo==="all"||r.fundo===fundo)&&(lote==="all"||[r.lugar,r.fundo,r.modulo,r.lote].join("|")===lote)&&(!from||r.date>=from)&&(!to||r.date<=to));
 const dimensions=[...new Set(analysis.map(r=>kind==="HUMEDADES"?String(r.prof):kind==="PRESIONES"?r.lado??"":"").filter(Boolean))].sort((a,b)=>a.localeCompare(b,undefined,{numeric:true}));
 const dim=tab==="mapa"&&dimension==="all"?(dimensions[0]??"all"):dimension;
 const selected=analysis.filter(r=>dim==="all"||(kind==="HUMEDADES"?String(r.prof)===dim:kind==="PRESIONES"?r.lado===dim:true));
 const series:{key:string;label:string;dimension?:string}[]=kind==="COMPACTACION"?[{key:"m1",label:"M1"},{key:"m2",label:"M2"},{key:"m3",label:"M3"}]:(dimension==="all"?dimensions:[dimension]).map((d,i)=>({key:"p"+i,label:kind==="HUMEDADES"?`Prof. ${d}${snapshot?.units.prof?" "+snapshot.units.prof:""}`:`Lado ${d}`,dimension:d}));
 function chartRows(by:"date"|"lot"){const groups=new Map<string,Measurement[]>();for(const r of selected){const k=by==="date"?r.date:[r.lugar,r.fundo,r.modulo,r.lote].join(" · ");groups.set(k,[...(groups.get(k)??[]),r]);}return [...groups].sort(([a],[b])=>a.localeCompare(b)).map(([label,rows])=>{const obj:Record<string,string|number|null>={label:by==="date"?dateLabel(label):label};series.forEach(s=>{const filtered=s.dimension?rows.filter(r=>kind==="HUMEDADES"?String(r.prof)===s.dimension:r.lado===s.dimension):rows;obj[s.key]=mean(filtered.map(r=>reading(r,s.key)).filter((v):v is number=>typeof v==="number"));});return obj;});}
 const unit=kind==="HUMEDADES"?"%":kind==="COMPACTACION"?snapshot?.units.compactacion??"":snapshot?.units.presion??"";
 const mapValues=snapshot?.geojson?.features.map(f=>mean(selected.filter(r=>matchesFeature(r,f)).map(r=>reading(r,metric)).filter((v):v is number=>typeof v==="number"))).filter((v):v is number=>v!==null)??[];
 const mappedCount=selected.filter(r=>snapshot?.geojson?.features.some(f=>matchesFeature(r,f))).length,pendingCount=all.filter(r=>r.pending||!r.synced).length;
 const options=(items:string[],first="Todos")=>[{value:"all",label:first},...items.map(v=>({value:v,label:v}))];
 const controls=<div className="filter-grid"><Picker label="Medición" value={kind} onChange={v=>{setKind(v as Kind);setDimension("all");}} options={KINDS.map(v=>({value:v,label:LABELS[v]}))}/><Picker label="Lugar" value={lugar} onChange={v=>{setLugar(v);setFundo("all");setLote("all");setDimension("all");}} options={options(unique("lugar"),"Todos los lugares")}/><Picker label="Fundo" value={fundo} onChange={v=>{setFundo(v);setLote("all");setDimension("all");}} options={options(unique("fundo",locations.filter(l=>lugar==="all"||l.lugar===lugar)),"Todos los fundos")}/><Picker label="Lote" value={lote} onChange={v=>{setLote(v);setDimension("all");}} options={[{value:"all",label:"Todos los lotes"},...[...new Map(locations.filter(l=>(lugar==="all"||l.lugar===lugar)&&(fundo==="all"||l.fundo===fundo)).map(l=>[[l.lugar,l.fundo,l.modulo,l.lote].join("|"),l])).entries()].map(([value,l])=>({value,label:[l.modulo,l.lote].join(" · ")}))]}/><label className="field"><span>Desde</span><input type="date" value={from} onChange={e=>{setFrom(e.target.value);setDimension("all");}} max={to||undefined}/></label><label className="field"><span>Hasta</span><input type="date" value={to} onChange={e=>{setTo(e.target.value);setDimension("all");}} min={from||undefined}/></label>{kind!=="COMPACTACION"&&<Picker label={kind==="HUMEDADES"?"Profundidad":"Lado"} value={dim} onChange={setDimension} options={tab==="mapa"&&dimensions.length?dimensions.map(v=>({value:v,label:v})):options(dimensions,kind==="HUMEDADES"?"Todas las profundidades":"Todos los lados")}/>} {tab==="mapa"&&kind==="COMPACTACION"&&<Picker label="Medición" value={metric} onChange={setMetric} options={["m1","m2","m3"].map(v=>({value:v,label:v.toUpperCase()}))}/>}</div>;

 async function scanLogin(){setBusy(true);setProblem("");try{const access=parseAccess(await scanAccess());if(access.endpoint){await configureEndpoint(access.endpoint);setConnectDraft(access.endpoint);}else if(connectDraft)await configureEndpoint(connectDraft);setCode(access.code);await api("activate",{code:access.code,principal:false});setAuthorized(true);await cache("activated",true);await flush();setCode("");}catch(e){if(e instanceof AccessError)setAuthorized(false);setProblem((e as Error).message);}finally{setBusy(false);}}
 useEffect(()=>{if(!Capacitor.isNativePlatform())return;let cancelled=false;let handle:{remove:()=>Promise<void>}|undefined;void NativeApp.addListener("appUrlOpen",event=>{try{if(authorized){toast("Este celular ya está activado.");return;}const access=parseAccess(event.url);setCode(access.code);setSharedEntry(v=>v+1);if(access.endpoint){setConnectDraft(access.endpoint);void configureEndpoint(access.endpoint).catch(e=>{if(e instanceof AccessError)setAuthorized(false);setProblem(e.message);});}}catch(e){if(e instanceof AccessError)setAuthorized(false);setProblem((e as Error).message);}}).then(h=>{if(cancelled)void h.remove();else handle=h;});return()=>{cancelled=true;void handle?.remove();};},[authorized]);
 if(!loaded)return <div className="startup"><Droplets size={36}/><p>Abriendo Riego…</p></div>;
 if(!authorized)return <><Toaster richColors/><RiegoOnboarding sharedEntry={sharedEntry} endpoint={connectDraft} code={code} busy={busy} online={online} problem={problem} onEndpoint={setConnectDraft} onCode={setCode} onActivate={activateDevice} onScan={scanLogin} onClearProblem={()=>setProblem("")} onShareSetup={()=>void shareText("Riego_Drive.gs",scriptSource).catch(e=>setProblem(e.message))}/></>;
 return <><Toaster richColors position="top-center"/><header className="topbar"><div className="topbar-inner"><div className="brand"><span className="brandmark"><Droplets size={26}/></span><div><strong>Riego</strong><span>Campo</span></div></div><div className="top-actions"><span className={`connection ${online?"":"offline"}`}>{online?<Wifi size={16}/>:<WifiOff size={16}/>}<span>{online?"En línea":"Sin conexión"}</span></span>{install&&<button className="quiet" onClick={async()=>{await install.prompt();await install.userChoice;setInstall(null);}}><Download size={18}/><span>Instalar app</span></button>}{snapshot?.owner&&<button className="quiet access-trigger" aria-label="Mis accesos" onClick={()=>setSettingsOpen(true)}><QrCode size={21}/><span>Mis accesos</span></button>}{!snapshot?.owner&&<button className="icon-button" aria-label="Cerrar acceso" onClick={()=>void logout()}><LogOut size={20}/></button>}</div></div></header>
 <main className="workspace"><div className="workspace-title"><div><p className="eyebrow">CONTROL DE RIEGO</p><h1>Mediciones de campo</h1>{snapshot?.owner&&<span className="device-label">Dispositivo principal{snapshot.profileName?" · "+snapshot.profileName:""}</span>}</div><button className="primary sync" onClick={()=>void sync()} disabled={busy||!online}><RefreshCw size={18} className={busy?"spinning":""}/><span>{busy?"Procesando…":"Sincronizar con Drive"}</span></button></div>
 {problem&&<div className="notice error-notice" role="alert">{problem}<button aria-label="Cerrar aviso" onClick={()=>setProblem("")}>×</button></div>}{!snapshot?.sourceConnected&&<div className="notice"><CloudUpload size={19}/><div><strong>Conexión con Drive pendiente.</strong> Puedes registrar mediciones; quedan guardadas en la app hasta conectar el archivo.</div>{snapshot?.owner&&<button className="text-button" onClick={()=>setSettingsOpen(true)}>Conectar</button>}</div>}
 <div className="stats"><div className="stat"><span>Mediciones</span><strong>{all.length.toLocaleString("es-PE")}</strong><span className="stat-note">En los tres apartados</span></div><div className="stat"><span>Lotes evaluados</span><strong>{new Set(all.map(r=>[r.lugar,r.fundo,r.modulo,r.lote].join("|"))).size}</strong><span className="stat-note">Con al menos una medición</span></div><div className="stat"><span>Pendientes de Drive</span><strong className={pendingCount?"amber":""}>{pendingCount}</strong><span className="stat-note">{queue.length?`${queue.length} todavía en este dispositivo`:"Guardados en la app"}</span></div><div className="stat"><span>Última sincronización</span><strong className="date-stat">{snapshot?.lastSync?new Intl.DateTimeFormat("es-PE",{timeZone:"America/Lima",day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit"}).format(new Date(snapshot.lastSync)):"Pendiente"}</strong><span className="stat-note">Archivo de Drive</span></div></div>
 <Tabs value={tab} onValueChange={v=>{setTab(v);setProblem("");if((KINDS as readonly string[]).includes(v)){setKind(v as Kind);setDimension("all");}}} className="modules"><TabsList className="module-tabs" aria-label="Apartados de riego">{NAV.map(n=><TabsTrigger key={n.id} value={n.id}><n.icon size={20}/><span>{n.label}</span></TabsTrigger>)}</TabsList>
 {KINDS.map(k=><TabsContent value={k} key={k}><div className="capture-grid"><section className="panel capture-panel"><div className="panel-heading"><div className="section-icon">{k==="HUMEDADES"?<Droplets/>:k==="PRESIONES"?<Gauge/>:<Layers/>}</div><div><p className="eyebrow">NUEVO REGISTRO</p><h2>{LABELS[k]}</h2></div></div><form onSubmit={submit}><div className="form-grid"><label className="field"><span>Fecha</span><input type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})} required/></label><Picker label="Lugar" value={form.lugar} onChange={v=>setForm({...form,lugar:v,fundo:"",modulo:"",lote:""})} options={[...new Set(["OLMOS","MOTUPE",...unique("lugar")])].map(v=>({value:v,label:v}))}/>
 {(["fundo","modulo","lote"] as const).map(key=><label className={`field ${key==="lote"?"wide":""}`} key={key}><span>{{fundo:"Fundo",modulo:"Módulo",lote:"Lote"}[key]}</span><input list={`list-${key}`} value={form[key]} onChange={e=>setForm(prev=>({...prev,[key]:e.target.value,...(key==="fundo"?{modulo:"",lote:""}:key==="modulo"?{lote:""}:{})}))} required maxLength={100} autoComplete="off"/><datalist id={`list-${key}`}>{[...new Set(locations.filter(l=>normalize(l.lugar)===normalize(form.lugar)&&(!form.fundo||key==="fundo"||normalize(l.fundo)===normalize(form.fundo))&&(!form.modulo||key!=="lote"||normalize(l.modulo)===normalize(form.modulo))).map(l=>l[key]))].filter(Boolean).map(v=><option key={v} value={v}/>)}</datalist></label>)}
 </div><div className="date-meta"><CalendarDays size={15}/>Año {form.date.slice(0,4)}<span>Mes {Number(form.date.slice(5,7))||"—"}</span><span>Semana {form.date?isoWeek(form.date):"—"}</span></div><div className="measurement-fields">{k==="HUMEDADES"&&<><NumberField label={`Profundidad${snapshot?.units.prof?" ("+snapshot.units.prof+")":""}`} name="prof" form={form} update={setForm}/><NumberField label="Humedad (%)" name="humedad" form={form} update={setForm} max={100}/></>}{k==="PRESIONES"&&<><label className="field"><span>Lado</span><input value={form.lado} onChange={e=>setForm({...form,lado:e.target.value})} required maxLength={100}/></label><NumberField label={`Presión final${snapshot?.units.presion?" ("+snapshot.units.presion+")":""}`} name="presion" form={form} update={setForm}/></>}{k==="COMPACTACION"&&<><label className="field wide"><span>Puntos</span><input value={form.puntos} onChange={e=>setForm({...form,puntos:e.target.value})} required maxLength={100}/></label>{["m1","m2","m3"].map(n=><NumberField key={n} label={n.toUpperCase()+(snapshot?.units.compactacion?" ("+snapshot.units.compactacion+")":"")} name={n} form={form} update={setForm}/>)}</>}</div><button className="primary full save" disabled={busy}><Plus size={19}/>{busy?"Guardando…":"Guardar medición"}</button><p className="form-note">{online?"Se guarda en la app. Sincroniza para enviarla a Drive.":"Se guarda en este dispositivo y se enviará al volver la conexión."}</p></form></section>
 <section className="panel recent-panel"><div className="panel-heading between"><div><p className="eyebrow">HISTORIAL</p><h2>Últimas mediciones</h2></div><span className="count-chip">{all.filter(r=>r.kind===k).length}</span></div>{!all.some(r=>r.kind===k)?<Blank title="Todavía no hay mediciones" detail={`Registra la primera medición de ${LABELS[k].toLowerCase()} o sincroniza los datos de Drive.`}/>:<Table className="record-table"><TableHeader><TableRow><TableHead>Fecha / lugar</TableHead><TableHead>Fundo / módulo</TableHead><TableHead>Lote</TableHead><TableHead>Medición</TableHead><TableHead>Estado</TableHead></TableRow></TableHeader><TableBody>{all.filter(r=>r.kind===k).slice(0,12).map(r=><TableRow key={r.id}><TableCell><strong>{dateLabel(r.date)}</strong><small>{r.lugar}</small></TableCell><TableCell><strong>{r.fundo}</strong><small>{r.modulo}</small></TableCell><TableCell>{r.lote}</TableCell><TableCell>{k==="HUMEDADES"?<><strong>{num(r.humedad)} %</strong><small>Prof. {r.prof} {snapshot?.units.prof}</small></>:k==="PRESIONES"?<><strong>{num(r.presion)} {snapshot?.units.presion}</strong><small>Lado {r.lado}</small></>:<><strong>{[r.m1,r.m2,r.m3].map(num).join(" / ")} {snapshot?.units.compactacion}</strong><small>Puntos: {r.puntos} · M1 / M2 / M3</small></>}</TableCell><TableCell><span className={`record-status ${r.synced?"done":"waiting"}`}>{r.synced?<Check size={13}/>:<CloudUpload size={13}/>} {r.pending?"Dispositivo":r.synced?"Drive":"App"}</span></TableCell></TableRow>)}</TableBody></Table>}<div className="panel-bottom"><button className="text-button" onClick={()=>{setKind(k);setTab("graficas");}}>Ver gráficas de {LABELS[k].toLowerCase()}</button></div></section></div></TabsContent>)}
 <TabsContent value="graficas"><section className="panel analysis-panel"><div className="panel-heading between"><div><p className="eyebrow">ANÁLISIS</p><h2>Evolución y comparación</h2></div><span className="count-chip">{selected.length} mediciones</span></div>{controls}</section><div className="charts-grid">{["date","lot"].map(by=><section className="panel chart-panel" key={by}><h3>{by==="date"?"Evolución por fecha":"Comparación por lote"}</h3><p className="chart-caption">{by==="date"?"Promedio diario":"Promedio de las mediciones filtradas"}{unit?" · "+unit:""}</p>{selected.length?<div className="chart"><ResponsiveContainer width="100%" height="100%">{by==="date"?<LineChart data={chartRows("date")} margin={{top:15,right:20,left:0,bottom:5}}><CartesianGrid stroke="#e5ecef" vertical={false}/><XAxis dataKey="label" tick={{fontSize:12}} tickMargin={10}/><YAxis tick={{fontSize:12}} width={45} domain={kind==="HUMEDADES"?[0,100]:[0,"auto"]}/><Tooltip/><Legend wrapperStyle={{fontSize:13}}/>{series.map((s,i)=><Line key={s.key} dataKey={s.key} name={s.label} stroke={COLORS[i%COLORS.length]} strokeWidth={2.5} connectNulls={false} dot={{r:3}}/>)}</LineChart>:<BarChart data={chartRows("lot")} margin={{top:15,right:20,left:0,bottom:5}}><CartesianGrid stroke="#e5ecef" vertical={false}/><XAxis dataKey="label" tick={false}/><YAxis tick={{fontSize:12}} width={45} domain={kind==="HUMEDADES"?[0,100]:[0,"auto"]}/><Tooltip/><Legend wrapperStyle={{fontSize:13}}/>{series.map((s,i)=><Bar key={s.key} dataKey={s.key} name={s.label} fill={COLORS[i%COLORS.length]} radius={[4,4,0,0]} maxBarSize={42}/>)}</BarChart>}</ResponsiveContainer></div>:<Blank title="Sin datos en este filtro" detail="Las gráficas se mostrarán cuando existan mediciones."/>}</section>)}</div></TabsContent>
 <TabsContent value="mapa"><section className="panel analysis-panel"><div className="panel-heading between"><div><p className="eyebrow">DISTRIBUCIÓN EN CAMPO</p><h2>Mapa de lotes</h2></div>{snapshot?.owner&&<button className="secondary" disabled={busy||!online} onClick={()=>mapInput.current?.click()}><MapPin size={17}/>{snapshot?.geojson?"Actualizar mapa":"Cargar GeoJSON"}</button>}</div>{controls}</section><section className="panel map-panel">{snapshot?.geojson?<><FieldMap geojson={snapshot.geojson} records={selected} metric={metric} unit={unit}/><div className="map-legend"><div><strong>Promedio por lote</strong><span>Escala relativa dentro del filtro</span></div><div className="color-scale"><span>{num(mapValues.length?Math.min(...mapValues):null)} {unit}</span><span className="gradient"/><span>{num(mapValues.length?Math.max(...mapValues):null)} {unit}</span></div><span className="no-data-key">Sin mediciones</span></div><p className="map-note">{mappedCount} de {selected.length} mediciones coinciden con un polígono. Los colores comparan valores; no indican límites agronómicos.</p></>:<div className="map-empty"><MapPinned size={48}/><h3>Falta el mapa de tus lotes</h3><p>Carga el GeoJSON de Fenología o Fitosanidad para vincular las mediciones a sus polígonos.</p>{snapshot?.owner&&<button className="primary" onClick={()=>mapInput.current?.click()} disabled={busy||!online}>Cargar mapa de lotes</button>}</div>}</section></TabsContent>
 </Tabs><footer className="workspace-footer"><span>Riego · v0.1.2</span><span>Humedades · Compactación · Presiones</span></footer></main>
 <input ref={mapInput} type="file" accept=".geojson,.json,application/geo+json,application/json" className="sr-only" onChange={e=>{const f=e.target.files?.[0];if(f)void importMap(f);e.target.value="";}}/>
 <Dialog open={settingsOpen} onOpenChange={setSettingsOpen}><DialogContent className="settings-dialog">
  <DialogTitle>Mis accesos</DialogTitle><DialogDescription>Desde tu dispositivo principal puedes dar acceso a cada celular de tu equipo.</DialogDescription>
  <div className="settings-scroll">
   <section className="access-section"><h3>Crear un acceso</h3><p>Cada código se usa una vez y vence en 24 horas.</p>
    <button className="primary" onClick={()=>void makeInvite()} disabled={busy||!online}><QrCode size={19}/>Generar código y QR</button>
    {invite&&<div className="invite"><img src={invite.qr} width={240} height={240} alt="QR para activar un dispositivo de riego"/>
     <strong className="invite-code">{invite.code.match(/.{1,4}/g)?.join(" ")}</strong>
     <span className="small">Vence: {new Intl.DateTimeFormat("es-PE",{timeZone:"America/Lima",dateStyle:"short",timeStyle:"short"}).format(new Date(invite.expiresAt))}</span>
     <div className="invite-actions">
      <button className="secondary" onClick={()=>void navigator.clipboard.writeText(invite.code).then(()=>toast.success("Código copiado"))}><Copy size={16}/>Copiar código</button>
      <button className="secondary" onClick={()=>void navigator.clipboard.writeText(invite.url).then(()=>toast.success("Acceso copiado"))}><Copy size={16}/>Copiar acceso completo</button>
      <button className="secondary" onClick={()=>void shareQr(invite.qr,invite.url).catch(e=>toast.error(e.message))}><Download size={16}/>Compartir QR</button>
     </div><p className="small">En el otro celular instala Riego y elige Tengo un código o QR. El QR o el acceso completo incluyen la conexión automáticamente.</p>
    </div>}
   </section>
   <details className="connection-details"><summary>Unidades y archivo de Drive</summary>
    <p><a href="https://docs.google.com/spreadsheets/d/1JgvxAAqxLuPGjLkBoj6XpHl3f8n_8Q9ouavMOb8BRfA/edit?usp=drivesdk" target="_blank" rel="noreferrer">Abrir mi archivo de riego</a></p>
    <div className="unit-grid">{[{key:"prof",label:"Unidad de profundidad"},{key:"compactacion",label:"Unidad de compactación"},{key:"presion",label:"Unidad de presión"}].map(u=><label className="field" key={u.key}><span>{u.label}</span><input value={unitDraft[u.key]??""} onChange={e=>setUnitDraft({...unitDraft,[u.key]:e.target.value})} maxLength={30}/></label>)}</div>
    <button className="secondary full" onClick={()=>void saveSettings()} disabled={busy||!online}>Guardar unidades</button>
   </details>
  </div>
 </DialogContent></Dialog>
 </>;
}
